# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'demo1_pod_import' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

      pod 'YYModel'

end
